### ISSUE TITLE
Twinklys as Join

### ISSUE THREAD

**Issue by Christoph-87** [thingzi/thingzi-logic-twinkly#2]
Hi, 

I have two physical twinkly devices as a virtual "join device" in the app. Is this kind of join device supported? 

If yes, what is the IP that needs to be given?

Sorry that I post this question here, but the Forum is disabled.

Best regards,
Christoph

![IMG_34D0319DBDF5-1](https://github.com/thingzi/thingzi-logic-twinkly/assets/77729959/398c354b-3297-420a-b174-39e424864ddd)

**Comment by bryzix** [comment]
Not sure actually.  I have linked lights for my Xmas decorations but checking my archived node red flow I turned them both on/off at same time.  

Maybe there is a better way to do this but I'd have to get them back down from the loft to test.

If you turn both on at same time are they still linked properly?

**Comment by Christoph-87** [comment]
Thanks a lot for the very quick reply. Yes, I tried this and it works to switch them both on and off at the same time and the last animation is still synchronized. 
I still think it would be great to have support for virtual devices such that it is more intuitive, but definitely not so urgent anymore. For me it works like this.
