### ISSUE TITLE
Node-Red crashes if parameter 'steps' is omitted or set to 1

### ISSUE THREAD

**Issue by groenerik** [thingzi/thingzi-logic-twinkly#3]
First of all thanks for sharing this project.

When playing around with the config parameters, I noticed some crashes of the entire Node-Red instance. 
 
I think the problem is in: twinkly-set.js

When the parameter 'steps' is not defined or configured <1, it is set to the value 1.

If steps has the value 1 it causes a division by zero in line 44.

`44            const stepFactor = 1 / (steps - 1);`

```
96                // Check step count
97                if (isNaN(color.steps) || color.steps < 1) {
98                    color.steps = 1;
99                }
```

**Comment by bryzix** [comment]
Hi, thanks for the great detail. i will take a look

**Comment by bryzix** [comment]
Hi, tried this just now and could reproduce this crash.  at the top of the function there is a check to prevent this...

![image](https://github.com/thingzi/thingzi-logic-twinkly/assets/46371227/b50ab5ff-2dd7-4bb3-b8ab-0b890044e775)

Are you able to share the color template json that broke it please?

**Comment by groenerik** [comment]
Yes, sure:

```
{
    "_msgid": "f3187d6b1fff730d",
    "payload": "on",
    "topic": "",
    "brightness": "100",
    "mode": "movie",
    "color": {
        "mode": "blink",
        "delay": 50,
        "steps": 1,
        "colors": [
            [
                255,
                0,
                0
            ],
            [
                0,
                255,
                0
            ],
            [
                0,
                0,
                255
            ]
        ]
    }
}
```

and 

```
{
    "_msgid": "f3187d6b1fff730d",
    "payload": "on",
    "topic": "",
    "brightness": "100",
    "mode": "movie",
    "color": {
        "mode": "blink",
        "delay": 50,
         "colors": [
            [
                255,
                0,
                0
            ],
            [
                0,
                255,
                0
            ],
            [
                0,
                0,
                255
            ]
        ]
    }
}

**Comment by groenerik** [comment]
and this the Node-Red log:

4 Nov 22:28:45 - [red] Uncaught Exception:
4 Nov 22:28:45 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "unknown color format 255,0,0".
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=20s expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 15.

**Comment by bryzix** [comment]
think ive resolved the issue now, thanks for pointers.  See how you go with v1.3.4

**Comment by groenerik** [comment]
Thanks for your quick response! I can confirm the fix!
