### ISSUE TITLE
Breaks after some time

### ISSUE THREAD

**Issue by hjuhlin** [thingzi/thingzi-logic-twinkly#4]
I'm using this node to check if the my Twinkly is on or off as a part of power usage calculation for all the lights in the house. 
It works great, but after some days the node stop working, and doesn't say anything when pinged. 
When I check debug checkbox and deploy the node starts to work again. I can then deselect the debug checkbox and deploy again and the node keeps working as normal for some days again. So something happens, but I don't know what. Can it be that the access token expires?

**Comment by bryzix** [comment]
Hi, are you able to share your flow?  Feel free to remove any auth details.  It's unlikely to be token expiry so worth a further look.

Worst case I can add some more debug info to help diagnose if it's not something obvious.

**Comment by hjuhlin** [comment]
Sure, my flow is very basic (for the part that is relevant to you) as I only use the get node to check if power is on or off. 

[
    {
        "id": "514e5c6695a5eb41",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "0c68f89ccbe2b497",
        "type": "thingzi-twinkly-get",
        "z": "514e5c6695a5eb41",
        "name": "",
        "address": "192.168.30.90",
        "debug": false,
        "x": 430,
        "y": 120,
        "wires": [
            [
                "51be608bb9f5562a"
            ]
        ]
    },
    {
        "id": "321d12d5937049a4",
        "type": "thingzi-twinkly-get",
        "z": "514e5c6695a5eb41",
        "name": "",
        "address": "192.168.30.64",
        "debug": false,
        "x": 430,
        "y": 160,
        "wires": [
            [
                "1616c51ddf7057ae"
            ]
        ]
    },
    {
        "id": "f9b5bd7fc0cf0256",
        "type": "inject",
        "z": "514e5c6695a5eb41",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "30",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 170,
        "y": 140,
        "wires": [
            [
                "0c68f89ccbe2b497",
                "321d12d5937049a4"
            ]
        ]
    },
    {
        "id": "51be608bb9f5562a",
        "type": "function",
        "z": "514e5c6695a5eb41",
        "name": "GetW",
        "func": "if (msg.payload==\"ON\") {\n    msg.payload = 34;\n} else {\n    msg.payload = 0;\n}\n\nmsg.topic = \"Twinkly Syren\"\n\nreturn msg;",
        "outputs": 1,
        "timeout": "",
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 630,
        "y": 120,
        "wires": [
            [
                "81512094c1994f2e"
            ]
        ]
    },
    {
        "id": "1616c51ddf7057ae",
        "type": "function",
        "z": "514e5c6695a5eb41",
        "name": "GetW",
        "func": "if (msg.payload==\"ON\") {\n    msg.payload = 34;\n} else {\n    msg.payload = 0;\n}\n\nmsg.topic = \"Twinkly Häck\"\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 630,
        "y": 160,
        "wires": [
            [
                "81512094c1994f2e"
            ]
        ]
    },
    {
        "id": "81512094c1994f2e",
        "type": "debug",
        "z": "514e5c6695a5eb41",
        "name": "debug 67",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 820,
        "y": 140,
        "wires": []
    }
]

**Comment by bryzix** [comment]
When the node does fail (and the debug box is checked) are there any useful messages in the node red debug log... e.g. it tried to re-authenticate and couldn't?

<img width="309" alt="image" src="https://github.com/thingzi/thingzi-logic-twinkly/assets/46371227/71f7b051-0024-48a6-bfb0-6dba55a36320">

**Comment by hjuhlin** [comment]
I will watch for it, but as it happens after some days I haven't had the debug checkbox checked at the right time. So will get back to when it happens after some days.

**Comment by bryzix** [comment]
Hi, managed to reproduce this.  It was caused when triggering the node and the connection failed.  From then on it just stared queuing requests.  Fix is in 1.3.7 so let me know how you get on

**Comment by hjuhlin** [comment]
Nice work! Installed now :) 

(I did mange to get 2 of 3 Twinkly nodes to stop, but did not mange to get the see the debug message when it happened, so was waiting for the last node to stop, but you fixed it bug before! Impressive :) )
