### ISSUE TITLE
Pre-Defined Colors for  thingzi-twinkly-set

### ISSUE THREAD

**Issue by Christoph-87** [thingzi/thingzi-logic-twinkly#5]
Would it be possible to pre-define some colors, like "red", "green", "blue",...  such that it is possible to use human readable color strings?

For example:

```
{
    "mode": "blink",  
    "delay": 50,  
    "steps": 10,  
    "colors": [
        "red",  
        "blue". 
    ]
}
```

**Comment by bryzix** [comment]
added an experimental feature in v1.4.0 e.g. 

```
{
    mode: "blink",
    delay: 25,
    steps: 25,
    presets: {
      red: [255, 0, 0],
      green: [0, 255, 0],
      blue: [255, 255, 255]
    },
    colors: [
      "red",
      [0, 255, 0],
      "blue"
    ]
  }
```

Which will let you mix and match pre-defined and inline colors :) Let me know if you spot any issues
